In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('moviesds.csv')

In [ ]:
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [ ]:
df.shape

(4803, 20)

In [ ]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",The Legend Ends,7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","Lost in our world, found in another.",6.1,43.926995

In [ ]:
df.isnull().sum()

title             0
overview          3
genres            0
tagline         844
vote_average      0
popularity        0
dtype: int64

In [ ]:
df=df.dropna(subset=['title'])

In [ ]:
df['overview']=df['overview'].fillna('')

In [ ]:
df.iloc[0]['genres']
# import ast

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
df['genres']=df['genres'].apply(lambda x:" ".join([i['name']for i in ast.literal_eval(x)]))

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995

In [ ]:
df['tagline']=df['tagline'].fillna('')

In [ ]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [ ]:
df['tags']=df['overview']+" "+df['genres']+df['tagline']

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950,Following the death of District Attorney Harve...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995,"John Carter is a war-weary, former military ca..."

In [ ]:
df['tags'][1]

'Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure Fantasy ActionAt the end of the world, the adventure begins.'

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words=set(stopwords.words('english'))
lematizer=WordNetLemmatizer()

In [ ]:
def preprocess_text(text):
  text=str(text).lower()
  text=re.sub(r'[^a-zA-Z\s]','',text)
  words=text.split()
  words=[word for word in words if word not in stop_words]
  words=[lematizer.lemmatize(word) for word in words]
  return " ".join(words)

In [ ]:
df['tags']=df['tags'].apply(preprocess_text)

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Avatar,"In the 22nd century, a paraplegic Marine is di...",Action Adventure Fantasy Science Fiction,Enter the World of Pandora.,7.2,150.437577,nd century paraplegic marine dispatched moon p...
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",Adventure Fantasy Action,"At the end of the world, the adventure begins.",6.9,139.082615,captain barbossa long believed dead come back ...
2,Spectre,A cryptic message from Bond’s past sends him o...,Action Adventure Crime,A Plan No One Escapes,6.3,107.376788,cryptic message bond past sends trail uncover ...
3,The Dark Knight Rises,Following the death of District Attorney Harve...,Action Crime Drama Thriller,The Legend Ends,7.6,112.312950,following death district attorney harvey dent ...
4,John Carter,"John Carter is a war-weary, former military ca...",Action Adventure Science Fiction,"Lost in our world, found in another.",6.1,43.926995,john carter warweary former military captain w...

In [ ]:
df['tags'][0]

'nd century paraplegic marine dispatched moon pandora unique mission becomes torn following order protecting alien civilization action adventure fantasy science fictionenter world pandora'

In [ ]:
df=df.reset_index(drop=True)

In [ ]:
indices=pd.Series(df.index,index=df['title']).drop_duplicates()
indices

title
Avatar                                         0
Pirates of the Caribbean: At World's End       1
Spectre                                        2
The Dark Knight Rises                          3
John Carter                                    4
                                            ...
El Mariachi                                 4798
Newlyweds                                   4799
Signed, Sealed, Delivered                   4800
Shanghai Calling                            4801
My Date with Drew                           4802
Length: 4803, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf=TfidfVectorizer(max_features=10000 ,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_matrix=tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 142769 stored elements and shape (4803, 10000)>

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def recommend(title,n=10):
  if title not in indices:
    return ['Movie not found']
  idx=indices[title]
  sim_scores=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
  similar_idx=sim_scores.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [ ]:
recommend("Titanic")

1269                                  Raise the Titanic
2143                                         Ghost Ship
2129                                     The Black Hole
2287                         I Can Do Bad All By Myself
3103                     The Chambermaid on the Titanic
3939                                               Tusk
4287                                            Niagara
171     Master and Commander: The Far Side of the World
57                                               WALL·E
770                                       Event Horizon
Name: title, dtype: object

In [ ]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pickle')
pickle.dump(tfidf,open('tfidf.pkl','wb'))